应该放在服务器根目录下

# 1. 网络与安全配置
# 允许外网访问（如果要用云服务器，必须设为 0.0.0.0，或者指定你的内网 IP）
bind 0.0.0.0
# 开启保护模式（必须设为 no，否则在外网无法通过密码连接）
protected-mode no
# Redis 监听的端口，默认 6379
port 6379

# 2. 强密码设置
requirepass Ab123456

# 3. 后台运行配置
# 如果你不希望退出终端后 Redis 就关掉，可以开启守护进程模式
# 注意：如果后续在云服务器用 Docker 启动 Redis，这里必须保持 no
daemonize no

# 4. 内存与持久化策略
# 内存满了以后的淘汰策略：报错，不淘汰任何点赞数据，保证落库前数据不丢
maxmemory-policy noeviction

# AOF 持久化
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec