server:
  port: 8080 #default port, 可以改

app:
  file-root-path: ${FILE_PATH:${user.dir}} #TODO: docker配置注入环境变量, 使用docker挂载卷
  base-url: ${BASE_URL:http://localhost:8080}

  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://127.0.0.1:5173,http://localhost:8080,http://127.0.0.1:8080}
    #TODO: docker配置时加上生产环境域名和前端IP

  # ==================== 新增：分片上传配置 ====================
  upload:
    temp-path: ${FILE_TEMP_PATH:${app.file-root-path}/temp/chunk/} # 分片临时目录
    storage-path: ${FILE_STORAGE_PATH:${app.file-root-path}/uploads/} # 正式文件目录
    chunk-size: 5242880 # 5MB 分片大小（固定）

spring:
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5432/threed_model_db} #先创建你的数据库 createdb xx_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
    
  web:
    resources:
      static-locations:
        # - file:uploads/
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:

      db-type: postgresql  # 指定数据库类型
