server:
  port: 8080 #default port, 可以改

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/threed_model_db #先创建你的数据库 createdb xx_db
    username: postgres
    password: Yw040925 #记得改
    driver-class-name: org.postgresql.Driver
    
  web:
    resources:
      static-locations:
        - file:uploads/


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:

      db-type: postgresql  # 指定数据库类型
